# Generated by Django 2.1.2 on 2018-12-25 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(db_column='CRS_ID', primary_key=True, serialize=False, verbose_name='서로게이트키')),
                ('name', models.CharField(db_column='CRS_Name', max_length=50, unique=True, verbose_name='과목명')),
                ('start_date', models.DateTimeField(db_column='CRS_StartDate', verbose_name='시작일')),
                ('end_date', models.DateTimeField(db_column='CRS_EndDate', verbose_name='종료일')),
                ('manager', models.ForeignKey(db_column='CRS_Manager', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='교수자')),
            ],
            options={
                'verbose_name': '과목: 기본 정보',
                'verbose_name_plural': '과목: 기본 정보',
                'db_table': 'Course',
                'ordering': ['id', 'manager__id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(db_column='LNG_ID', primary_key=True, serialize=False, verbose_name='서로게이트키')),
                ('language', models.CharField(db_column='CRS_Language', max_length=50, unique=True, verbose_name='언어(버전)')),
                ('compile_message', models.CharField(blank=True, db_column='CRS_CompileMessage', max_length=50, null=True, verbose_name='컴파일 메세지')),
                ('run_message', models.CharField(db_column='CRS_RunMessage', max_length=50, verbose_name='실행 메세지')),
            ],
            options={
                'verbose_name': '언어: 프로그래밍 언어',
                'verbose_name_plural': '언어: 프로그래밍 언어',
                'db_table': 'Language',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LanguageOfCourse',
            fields=[
                ('id', models.AutoField(db_column='LOC_ID', primary_key=True, serialize=False, verbose_name='서로게이트키')),
                ('course', models.ForeignKey(db_column='LOC_Course', on_delete=django.db.models.deletion.CASCADE, to='algolab_class_API.Course', verbose_name='수업')),
                ('language', models.ForeignKey(db_column='LOC_Language', on_delete=django.db.models.deletion.CASCADE, to='algolab_class_API.Language', verbose_name='언어')),
            ],
            options={
                'verbose_name': '과목: 사용 언어',
                'verbose_name_plural': '과목: 사용 언어',
                'db_table': 'LanguageOfCourse',
                'ordering': ['id', 'course__id'],
            },
        ),
        migrations.CreateModel(
            name='StudentInCourse',
            fields=[
                ('id', models.AutoField(db_column='SIC_ID', primary_key=True, serialize=False, verbose_name='서로게이트키')),
                ('course', models.ForeignKey(db_column='SIC_Course', on_delete=django.db.models.deletion.CASCADE, to='algolab_class_API.Course', verbose_name='수업')),
                ('student', models.ForeignKey(db_column='SIC_Language', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='언어')),
            ],
            options={
                'verbose_name': '과목: 수강 학생',
                'verbose_name_plural': '과목: 수강 학생',
                'db_table': 'StudentInCourse',
                'ordering': ['id', 'course__id'],
            },
        ),
    ]
