# Generated by Django 2.1.4 on 2018-12-26 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('algolab_class_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='서로게이트키')),
                ('context', models.TextField(db_column='Context', verbose_name='내용')),
                ('contextType', models.CharField(db_column='ContextType', max_length=10, verbose_name='글 종류')),
                ('writer', models.ForeignKey(db_column='Writer', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시판: 기본 정보',
                'verbose_name_plural': '게시판: 기본 정보',
                'db_table': 'Board',
                'ordering': ['id'],
            },
        ),
    ]
