# Generated by Django 2.1.4 on 2018-12-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algolab_class_API', '0003_auto_20181226_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='contextType',
            field=models.CharField(choices=[('NOTICE', '공지사항'), ('QUESTION', '질문')], db_column='ContextType', default='QUESTION', max_length=10, verbose_name='글 종류'),
        ),
        migrations.DeleteModel(
            name='ContextTypeOfBoard',
        ),
    ]
