# Generated by Django 2.1.4 on 2018-12-27 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('algolab_class_API', '0005_auto_20181227_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
                ('authority', models.CharField(choices=[('STUDENT', '학생'), ('MENTOR', '멘토'), ('CLASS_MANAGER', '과목관리자'), ('SERVER_MANAGER', '서버관리자')], db_column='Authority', max_length=20, verbose_name='권한')),
            ],
        ),
        migrations.AlterField(
            model_name='problemincourse',
            name='problem',
            field=models.ForeignKey(db_column='Problem', on_delete=django.db.models.deletion.CASCADE, to='algolab_class_API.Problem', verbose_name='문제'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='problem',
            field=models.ForeignKey(db_column='Problem', on_delete=django.db.models.deletion.CASCADE, to='algolab_class_API.Problem', verbose_name='문제'),
        ),
    ]
