# Generated by Django 2.1.4 on 2018-12-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algolab_class_API', '0006_auto_20181227_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['user__name'], 'verbose_name': '유저: 기본 정보', 'verbose_name_plural': '유저: 기본 정보'},
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='UserInfo',
        ),
    ]
