# Generated by Django 2.1.4 on 2018-12-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algolab_class_API', '0007_auto_20181227_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['user__username'], 'verbose_name': '유저: 기본 정보', 'verbose_name_plural': '유저: 기본 정보'},
        ),
    ]
