# Generated by Django 2.1.4 on 2018-12-27 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('algolab_class_API', '0008_auto_20181227_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardQuestion',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='서로게이트키')),
                ('title', models.CharField(db_column='Title', max_length=50, verbose_name='글 제목')),
                ('context', models.TextField(db_column='Context', verbose_name='내용')),
                ('context_type', models.CharField(choices=[('NOTICE', '공지사항'), ('QUESTION', '질문')], db_column='ContextType', default='QUESTION', max_length=10, verbose_name='글 종류')),
                ('write_time', models.DateTimeField(auto_now_add=True, db_column='WriteTime', verbose_name='작성 시간')),
                ('problem', models.ForeignKey(db_column='Problem', on_delete=django.db.models.deletion.DO_NOTHING, to='algolab_class_API.Problem', verbose_name='문제')),
                ('writer', models.ForeignKey(db_column='Writer', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시판: 질문 정보',
                'verbose_name_plural': '게시판: 질문 정보',
                'db_table': 'BoardQuestion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BoardReply',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='서로게이트키')),
                ('context', models.TextField(db_column='Context', verbose_name='내용')),
                ('write_time', models.DateTimeField(auto_now_add=True, db_column='WriteTime', verbose_name='작성 시간')),
                ('question', models.ForeignKey(db_column='Question', on_delete=django.db.models.deletion.CASCADE, to='algolab_class_API.BoardQuestion', verbose_name='질문 문제')),
                ('writer', models.ForeignKey(db_column='Writer', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시판: 답변 정보',
                'verbose_name_plural': '게시판: 답변 정보',
                'db_table': 'BoardReply',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='board',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
