# Generated by Django 2.1.4 on 2018-12-28 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('algolab_class_API', '0009_auto_20181227_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitHistory',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='서로게이트키')),
                ('status', models.CharField(choices=[('SOLVED', 'Solved'), ('COMPILE_ERROR', 'CompileError'), ('TIME_OVER', 'TimeOver'), ('RUNTIME_ERROR', 'RuntimeError')], db_column='Status', max_length=10, verbose_name='제출 결과')),
                ('code', models.TextField(db_column='Code', verbose_name='제출 코드')),
                ('submit_time', models.DateTimeField(auto_now_add=True, db_column='SubmitTime', verbose_name='제출 시간')),
                ('language', models.ForeignKey(db_column='Language', on_delete=django.db.models.deletion.DO_NOTHING, to='algolab_class_API.Language', verbose_name='언어')),
                ('problem', models.ForeignKey(db_column='Problem', on_delete=django.db.models.deletion.DO_NOTHING, to='algolab_class_API.ProblemInCourse', verbose_name='문제')),
                ('user', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='제출자')),
            ],
            options={
                'verbose_name': '제출 기록',
                'verbose_name_plural': '제출 기록',
                'db_table': 'SubmitHistory',
                'ordering': ['id'],
            },
        ),
    ]
